#include "../base/base_inc.h"
#include "../os/os_inc.c"
#include "../base/base_inc.c"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

typedef struct Shader_Info Shader_Info;
struct Shader_Info {
    const char *filename;
    const char *var_name;
    const char *type; // "vert" or "frag"
};

// Shader list
static Shader_Info shaders[] = {
    {"rect.vert", "rect_vert", "vert"},
    {"rect.frag", "rect_frag", "frag"},
    {"blur.vert", "blur_vert", "vert"},
    {"blur.frag", "blur_frag", "frag"},
    {"mesh.vert", "mesh_vert", "vert"},
    {"mesh.frag", "mesh_frag", "frag"},
};
static const u64 shader_count = sizeof(shaders) / sizeof(shaders[0]);

internal String
compile_glsl_to_spirv(Arena *arena, const char *glsl_path) {
    String result = {0};

    // Create temp output path
    char temp_spv[256];
    snprintf(temp_spv, sizeof(temp_spv), "/tmp/shader_%lu.spv", (u64)time(0));

    // Build glslangValidator command
    char cmd[512];
    snprintf(cmd, sizeof(cmd), "glslangValidator -V \"%s\" -o \"%s\"", glsl_path, temp_spv);

    printf("  Running: %s\n", cmd);

    // Run compiler
    int exit_code = system(cmd);
    if (exit_code != 0) {
        printf("Error: Failed to compile %s\n", glsl_path);
        return result;
    }

    // Read compiled SPIR-V
    FILE *f = fopen(temp_spv, "rb");
    if (!f) {
        printf("Error: Could not read compiled SPIR-V from %s\n", temp_spv);
        return result;
    }

    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);

    if (size > 0) {
        u8 *data = push_array(arena, u8, size);
        fread(data, 1, size, f);
        result.data = data;
        result.size = size;
    }

    fclose(f);

    // Clean up temp file
    char rm_cmd[512];
    int  ret = snprintf(rm_cmd, sizeof(rm_cmd), "rm -f \"%s\"", temp_spv);
    if (ret > 0 && ret < (int)sizeof(rm_cmd)) {
        system(rm_cmd);
    }

    return result;
}

internal void
generate_shader_c_array(Arena *arena, FILE *out_c, FILE *out_h, const char *var_name, String spirv_data) {
    // Write to .c file
    fprintf(out_c, "const unsigned char renderer_vulkan_%s_shader_src[] = {\n",
            var_name);

    for (u64 i = 0; i < spirv_data.size; i++) {
        if (i % 16 == 0)
            fprintf(out_c, "    ");
        fprintf(out_c, "0x%02x", spirv_data.data[i]);
        if (i < spirv_data.size - 1)
            fprintf(out_c, ",");
        if ((i + 1) % 16 == 0 || i == spirv_data.size - 1)
            fprintf(out_c, "\n");
        else
            fprintf(out_c, " ");
    }

    fprintf(out_c, "};\n");
    fprintf(out_c, "const unsigned int renderer_vulkan_%s_shader_src_size = %u;\n\n",
            var_name, spirv_data.size);

    // Write to .h file
    fprintf(out_h, "extern const unsigned char renderer_vulkan_%s_shader_src[];\n",
            var_name);
    fprintf(out_h, "extern const unsigned int renderer_vulkan_%s_shader_src_size;\n",
            var_name);
}

internal b32
file_exists(const char *path) {
    FILE *f = fopen(path, "r");
    if (f) {
        fclose(f);
        return true;
    }
    return false;
}

int main(int argc, char **argv) {
    Arena *arena = arena_alloc();

    printf("Kanso Meta Build Tool\n");
    printf("Generating shader sources...\n");

    // Check if glslangValidator is available
    int validator_check = system("command -v glslangValidator >/dev/null 2>&1");
    if (validator_check != 0) {
        printf("Error: glslangValidator not found. Install glslang-tools.\n");
        printf("On Ubuntu/Debian: sudo apt install glslang-tools\n");
        printf("On Arch: sudo pacman -S glslang\n");
        return 1;
    }

    // Create generated files
    FILE *out_c = fopen("src/generated/vulkan_shaders.c", "w");
    FILE *out_h = fopen("src/generated/vulkan_shaders.h", "w");

    if (!out_c || !out_h) {
        printf("Error: Could not create generated files\n");
        return 1;
    }

    // Write file headers
    fprintf(out_c, "// Auto-generated Vulkan shader sources\n");
    fprintf(out_c, "// Generated by meta.c\n\n");
    fprintf(out_c, "#include \"vulkan_shaders.h\"\n\n");

    fprintf(out_h, "// Auto-generated Vulkan shader sources\n");
    fprintf(out_h, "// Generated by meta.c\n\n");
    fprintf(out_h, "#pragma once\n\n");

    // Process each shader
    for (u64 i = 0; i < shader_count; i++) {
        Shader_Info *shader = &shaders[i];
        char         shader_path[256];
        snprintf(shader_path, sizeof(shader_path), "src/renderer/shaders/glsl/%s",
                 shader->filename);

        printf("Processing %s...\n", shader->filename);

        if (!file_exists(shader_path)) {
            printf("Error: Shader file not found: %s\n", shader_path);
            fclose(out_c);
            fclose(out_h);
            return 1;
        }

        String spirv_data = compile_glsl_to_spirv(arena, shader_path);
        if (spirv_data.size == 0) {
            printf("Error: Failed to compile shader %s\n", shader->filename);
            fclose(out_c);
            fclose(out_h);
            return 1;
        }

        printf("  Compiled %lu bytes of SPIR-V\n", (u64)spirv_data.size);
        generate_shader_c_array(arena, out_c, out_h, shader->var_name, spirv_data);
    }

    fclose(out_c);
    fclose(out_h);

    printf("Generated src/generated/vulkan_shaders.c and vulkan_shaders.h\n");
    printf("Meta build complete!\n");

    return 0;
}
