# Makefile wrapper for CMake
BUILD_TYPE ?= Debug
BUILD_DIR = build
BINARY_NAME = kanso

.PHONY: all clean debug release run run-release configure lint help

# Default target
all: configure
	@cd $(BUILD_DIR) && $(MAKE)

# Configure CMake if needed
configure:
	@if [ ! -f $(BUILD_DIR)/Makefile ]; then \
		echo "Configuring CMake..."; \
		mkdir -p $(BUILD_DIR); \
		cd $(BUILD_DIR) && cmake -DCMAKE_BUILD_TYPE=$(BUILD_TYPE) ..; \
	fi

# Debug build
debug:
	@$(MAKE) BUILD_TYPE=Debug

# Release build  
release:
	@$(MAKE) BUILD_TYPE=Release

# Clean build directory
clean:
	@echo "Cleaning build directory..."
	@rm -rf $(BUILD_DIR) compile_commands.json

# Run the binary
run: all
	@if [ -f ./$(BUILD_DIR)/$(BINARY_NAME) ]; then \
		./$(BUILD_DIR)/$(BINARY_NAME); \
	elif [ -f ./$(BUILD_DIR)/debug/$(BINARY_NAME) ]; then \
		./$(BUILD_DIR)/debug/$(BINARY_NAME); \
	elif [ -f ./$(BUILD_DIR)/release/$(BINARY_NAME) ]; then \
		./$(BUILD_DIR)/release/$(BINARY_NAME); \
	else \
		echo "Error: Cannot find binary $(BINARY_NAME)"; \
		exit 1; \
	fi

# Run release build
run-release:
	@$(MAKE) BUILD_TYPE=Release run

# Lint the code
lint:
	@echo "Running linter..."
	@find src -name "*.cpp" -o -name "*.h" | xargs clang-format --dry-run --Werror 2>/dev/null || \
		(echo "Code style issues found. Run 'make format' to fix." && exit 1)

# Format the code
format:
	@echo "Formatting code..."
	@find src -name "*.cpp" -o -name "*.h" | xargs clang-format -i

# Force reconfigure
reconfigure:
	@rm -rf $(BUILD_DIR)
	@$(MAKE) configure

help:
	@echo "Available targets:"
	@echo "  make           - Build with current BUILD_TYPE (default: Debug)"
	@echo "  make debug     - Build debug version"
	@echo "  make release   - Build release version"
	@echo "  make clean     - Remove build files"
	@echo "  make run       - Build and run the program"
	@echo "  make run-release - Build and run release version"
	@echo "  make lint      - Check code formatting"
	@echo "  make format    - Auto-format code"
	@echo "  make reconfigure - Force CMake reconfiguration"
	@echo ""
	@echo "Variables:"
	@echo "  BUILD_TYPE=Debug|Release (default: Debug)"
	@echo ""
	@echo "Note: compile_commands.json is automatically generated by CMake"